version: 2
jobs:
  build:
    docker:
      - image: alpine:3.10.2

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "package.json" }}
#            # fallback to using the latest cache if no exact match is found
#            - v1-dependencies-

      - run:
          name: Install dependencies
          command: apk add g++ nodejs npm

      - run: npm ci && npx lerna bootstrap && npm config set npm_config_unsafe_perm true

#      - save_cache:
#          paths:
#            - node_modules
#          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run build && npm run test